format = '''\\
$username@$hostname:$directory $git_branch $git_status $python
îœ’ \\
îš‘\\
$status
'''

[username]
style_user = 'fg:red bold'
show_always = true
format = '[$user]($style)'

[hostname]
ssh_only = false
style = "fg:green bold"
format = '[$ssh_symbol$hostname]($style)'

[directory]
style = "fg:blue bold"
read_only = "[ï€£]"
format = '[$path $read_only]($style)'
#truncation_symbol = "â€¦/"
truncation_length = -1

[git_branch]
symbol = ""
style = "fg:bright-red"
format = '[â”€\[](fg:red)[$branch]($style)[\]](fg:red)'

[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'
# ahead = 'â‡¡${count}'
# diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
# behind = 'â‡£${count}'
style = "fg:bright-green"
format = '[\[](fg:green)[$all_status$ahead_behind]($style)[\]](fg:green)'

[java]
style = "fg:bright-black"
format = '[ î‚° ](fg:black)[$symbol${version}]($style)'
symbol = "[î‰– ](fg:#d65d0e)"

[nodejs]
style = "fg:bright-black"
format = '[ î‚° ](fg:black)[${version}]($style) '
symbol = "[îœ˜ ](fg:green)"

[python]
style = "fg:bright-blue"
format = '[ î‚° ](fg:blue)[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
version_format = 'v${major}.${minor}'
symbol = "[îˆµ ](fg:#417fb1)"

[rust]
style = "fg:bright-black"
format = '[ î‚° ](fg:black)[${symbol}${version}]($style) '
symbol = "[î¨ ](fg:yellow)"

[cmd_duration]
style = "fg:yellow"
min_time = 1
show_milliseconds = true
format = '[\[](fg:red)[â± $duration]($style)[\]](fg:red)'

[shell]
fish_indicator = 'ó°ˆº '
bash_indicator = 'ó±†ƒ'
zsh_indicator = 'ó±†ƒ'
powershell_indicator = 'ï‘ _'
unknown_indicator = 'ï†—'
style = 'cyan bold'
disabled = false

[status]
style = 'fg:white'
symbol = '[ï¡ ](fg:bright-red)'
success_symbol = '[ï¡ ](fg:bright-green)'
format = '[$symbol]($style) '
map_symbol = true
disabled = false

